server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect